### ISSUE TITLE
[ERROR]webpack build

### ISSUE THREAD

**Issue by Tommassissimo** [IjzerenHein/famous-flex-datepicker#2] opened 2015-03-20 04:57 UTC
I clone the project and install all tools required by documentation, but when I try to use webpack build the dist file, it fails and seem some module not found but actually I already install them via "npm install" command, anyone can help me figure out the reason.
![69517c67-9d62-437b-a35a-3c8f7e25ba54](https://cloud.githubusercontent.com/assets/1832223/6746266/41bf0472-cf00-11e4-99f3-75f1b3015a3d.png)

**Comment by IjzerenHein** [comment] 2015-03-20 07:24
Hi, I just fixed the problem, it should work now.

**Comment by Tommassissimo** [comment] 2015-03-20 07:27
Thanks, I will try it again now. The datepicker is really cool!
Yes,it fixed!

**Comment by IjzerenHein** [comment] 2015-03-20 07:31
Awesome, glad you like it, and the problem is fixed now!

**Closed as completed** 2015-03-20 07:30 UTC
Labels: bug
